#!/usr/bin/env python3
"""
Code Writer Skill
Writes code to files in the workspace after successful generation/execution
"""
import os
import json
import sys
from pathlib import Path
from datetime import datetime


def main():
    """Write code to file"""
    try:
        params_json = os.environ.get("SKILL_PARAMS", "{}")
        params = json.loads(params_json)
        
        code = params.get("code", "")
        filename = params.get("filename", "")
        description = params.get("description", "")
        language = params.get("language", "python")
        
        if not code:
            print(json.dumps({
                "success": False,
                "error": "No code provided to write"
            }))
            sys.exit(1)
        
        if not filename:
            # Auto-generate filename based on language
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            extensions = {
                "python": "py",
                "javascript": "js",
                "java": "java",
                "go": "go",
                "rust": "rs"
            }
            ext = extensions.get(language.lower(), "txt")
            filename = f"generated_code_{timestamp}.{ext}"
        
        # Ensure workspace directory exists
        workspace_dir = Path("/workspace")
        workspace_dir.mkdir(parents=True, exist_ok=True)
        
        # Full file path
        file_path = workspace_dir / filename
        
        # Add header comment if description provided
        if description:
            comment_styles = {
                "python": "#",
                "javascript": "//",
                "java": "//",
                "go": "//",
                "rust": "//"
            }
            comment = comment_styles.get(language.lower(), "#")
            header = f"{comment} {description}\n{comment} Generated by OpenClaw Agent\n{comment} {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
            code = header + code
        
        # Write file
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(code)
        
        # Calculate file size
        file_size = file_path.stat().st_size
        
        output = {
            "success": True,
            "filename": filename,
            "filepath": str(file_path),
            "file_size": file_size,
            "lines_of_code": len(code.split('\n')),
            "language": language,
            "message": f"Code written to {filename}",
            "location": f"/workspace/{filename}",
            "description": description if description else "Code file"
        }
        
        print(json.dumps(output, indent=2))
    
    except Exception as e:
        print(json.dumps({
            "success": False,
            "error": str(e)
        }))
        sys.exit(1)


if __name__ == "__main__":
    main()