import asyncio
import os
from pathlib import Path
from dotenv import load_dotenv

env_path = Path(__file__).parent.parent / ".env"
load_dotenv(env_path)

from loguru import logger
from app.agents.qa_specialist_agent import qa_specialist

async def test_qa_agent():
    logger.info("Starting QA Agent Verification Test...")
    
    # Simulate a buggy calculator generated by the Code Specialist
    buggy_code = """
def add(a, b): return a + b
def subtract(a, b): return a - b
def multiply(a, b): return a * b
def divide(a, b): 
    # Bug: returns addition instead of division!
    return a + b
"""
    
    files = {"calculator.py": buggy_code.strip()}
    
    # Ask QA an agent to verify it
    request = "Write a calculator module with add, subtract, multiply, and divide."
    
    result = await qa_specialist.verify_code(
        files=files,
        project_type="python",
        original_request=request
    )
    
    if result.get("tests_passed"):
        logger.error("❌ QA Agent reported tests passed for buggy code!")
    else:
        logger.info("✅ QA Agent successfully caught the bug!")
        logger.info(f"Feedback:\n{result.get('feedback')}")
        
    print("\n\n--- RAW OUTPUT ---")
    print(result.get("test_output", ""))

if __name__ == "__main__":
    asyncio.run(test_qa_agent())
